name: test-quarkus-staging
on:
  push:
    branches:
      - develop
permissions:
  packages: write

jobs:
  build:
    name: Build And Push
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.output-tag.outputs.image-tag }}
    steps:
      # set Image Tag
      - name: Set Image Tag
        id: output-tag
        run: |
          echo "image-tag=$GITHUB_SHA" >> $GITHUB_ENV
          echo "::set-output name=image-tag::$GITHUB_SHA"
      # checkout repository
      - uses: actions/checkout@v3
      # set up JDK version
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      # cache maven dependency
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # build project
      - name: Build And Push To Github Package
        run: >
          mvn clean package 
          -pl test-quarkus -am
          -DskipTests
          -Dquarkus.container-image.registry=ghcr.io
          -Dquarkus.container-image.group=ghcr.io/kuoche1712003
          -Dquarkus.container-image.name=test-quarkus-staging
          -Dquarkus.container-image.username=${{ github.actor }}
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }}
          -Dquarkus.container-image.build=true
          -Dquarkus.container-image.push=true
          -Dquarkus.container-image.tag=${{ env.image-tag }}